ALTER TABLE communities 
ADD COLUMN IF NOT EXISTS code VARCHAR(50),
ADD COLUMN IF NOT EXISTS address VARCHAR(255),
ADD COLUMN IF NOT EXISTS city VARCHAR(100),
ADD COLUMN IF NOT EXISTS state VARCHAR(100),
ADD COLUMN IF NOT EXISTS country VARCHAR(100),
ADD COLUMN IF NOT EXISTS postal_code VARCHAR(20),
ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS buildings_count INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS blocks_count INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS total_flats INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'ACTIVE',
ADD COLUMN IF NOT EXISTS logo_url TEXT,
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS currency VARCHAR(10) DEFAULT 'INR',
ADD COLUMN IF NOT EXISTS water_unit VARCHAR(10) DEFAULT 'L',
ADD COLUMN IF NOT EXISTS billing_cycle VARCHAR(20) DEFAULT 'MONTHLY';

-- Populate default code for existing records if any
UPDATE communities SET code = 'COM-' || id WHERE code IS NULL;

-- Enforce UNIQUE constraint after seeding code for existing records
ALTER TABLE communities ADD CONSTRAINT unique_community_code UNIQUE (code);
